### ISSUE TITLE
[Tracking] Kubecost Helm Chart Redesign .NEXT

### ISSUE THREAD

**Issue by chipzoller** [kubecost/cost-analyzer-helm-chart#2672]
This is a tracking issue for changes desired in the next major version of the Helm chart. It will be updated over time as the project plan is built.

- [ ] Rename repository to "kubecost-helm-chart"
- [ ] Remove subcharts and move to single chart
- [ ] Consolidate [cost-analyzer](https://github.com/kubecost/cost-analyzer) repository into this one
- [ ] Consolidate [openshift-helm-chart](https://github.com/kubecost/openshift-helm-chart) into this one
- [ ] Use feature level abstraction for values

**Comment by chipzoller** [comment]
Converted to internal doc.
